### ISSUE TITLE
Installation from local path and loading

### ISSUE THREAD

**Issue by MacGyer** [getkirby/composer-installer#4]
Hey guys,

I have a Kirby installation (3.6.2) and the whole installation is based on Composer and Git.

To develop my own blocks and provide them via plugin I have the following folder structure:

![image](https://user-images.githubusercontent.com/2939625/156936891-278b3779-0b0f-496c-80d2-b3d456edcf14.png)

Meaning: the plugin source code resides in `site/ext/plugins/macgyer-blocks` (I don't need a own repo for this, do I?) and is required by local installation path in `composer.json`:

```
"repositories": [
    {
        "type": "path",
        "url": "./ext/plugins/*",
        "options": {
            "symlink": false
        }
    }
],
"require": {
    "php": "^7.4",
    "getkirby/cms": "^3.0",
    "macgyer/macgyer-blocks": "*"
},
```

The process is successfully installing the plugin in `site/web/site/plugins` by mirroring the source.

When debugging the plugin code my breakpoints did not stop execution and so I dived into the loading of the blocks plugin.

I noticed, the plugin code in `site/web/site/plugins` was not executed, instead the code from the mirror source path seems to be used (`site/ext/plugins`). I could verify this by inspecting the file locating process in https://github.com/getkirby/kirby/blob/main/config/components.php#L300 which returned the path from `site/ext/plugins` instead of `site/web/site/plugins`.

![image](https://user-images.githubusercontent.com/2939625/156937308-ba9bad25-7535-4132-a5f7-663fa372809d.png)

Which might be because `$kirby->extensions->snippets` contains exactly this path:

![image](https://user-images.githubusercontent.com/2939625/156937368-55bb1e62-a335-437d-9ef0-c76846412e40.png)

Why is this happening?

For the record, here is the composer.json of the plugin:

```
{
    "name": "macgyer/macgyer-blocks",
    "description": "Block definition for website",
    "version": "1.0.0",
    "type": "kirby-plugin",
    "minimum-stability": "stable",
    "license": "proprietary",
    "authors": [
        {
            "name": "Christoph",
            "email": "email@example.com"
        }
    ],
    "require": {
        "getkirby/composer-installer": "^1.1"
    },
    "config": {
        "optimize-autoloader": true
    }
}
```

If you need additional information feel free to ask.
If this issue has to be opened in the Kirby repo I can move this over.

Cheers and thanks for help.

**Comment by lukasbestle** [comment]
Are you sure that Composer didn't create a symbolic link? What you describe strongly suggests that. I see you have disabled the `symlink` option in your repository config, but it looks like it is not respected by Composer.

**Comment by MacGyer** [comment]
Composer is working as expected:

When setting `"symlink": true` it creates a symlink, when not it mirrors without symlink

**Comment by lukasbestle** [comment]
Could you please post the `index.php` of your plugin?

**Comment by MacGyer** [comment]
```php

Kirby::plugin('macgyer/macgyer-blocks', [
    'blueprints' => [
        'blocks/slider' => __DIR__ . '/blueprints/blocks/slider.yml',
    ],
    'snippets' => [
        'blocks/slider' => __DIR__ . '/snippets/blocks/slider.php',
    ],
    'options' => [
        'cache' => false
    ]
]);
```

I have an assumption (but not tested yet):
Might be the ```__DIR__``` constant?

**Comment by lukasbestle** [comment]
Yes, it's the only part that I believe could cause this. Kirby uses the provided path as is.

Might be PHP's OPcache. It also caches such paths and if the cache is mistakenly used for the same file at a different path, then PHP will use the wrong path. You can rule that out by clearing the OPcache (e.g. by restarting your PHP process).

**Comment by MacGyer** [comment]
Thanks for your input.

I disabled OPcache, removed the plugin from target dir, ran composer update without symlinks and ... it worked!
Did the same with symlinking again, worked too.

Enabled OPcache again, removed plugin, ran composer update with and without symlinking. Both ways worked.
Who knows, maybe it was just some hickup with OPcache. Will observe the matter and re-open the issue if needed.

Wish you a sunny Sunday and all the best.
Cheers
